Create a Student class that encapsulates the student's name, age, and grades. Provide methods to get and set the grades.

Define the Class Structure:
* Create a class named Student.
    * Define an \_\_init\_\_ method to initialize the instance variables name, age, and grades.
    * grades is a list with default value None
    * Use private attributes to encapsulate the data.

* Write a Method to Set Grades:
    * Define a set_grade method that takes a grade as a parameter and appends it to the grades list.

* Write a Method to Get Grades:
    * Define a get_grades method to return the list of grades.

In [2]:
class Student:
    def __init__(self, name, age, grades=None):
        self.__name = name
        self.__age = age
        self.__grades = grades if grades else []

    def set_grade(self, grade):
        self.__grades.append(grade)

    def get_grades(self):
        return self.__grades

student = Student("Cole", 21)
student.set_grade(90)
student.set_grade(85)
print(student.get_grades())  

[90, 85]


Create a Car class with a private attribute speed. Implement methods to accelerate and decelerate the car.
* Create a private instance variable speed and set its initial value to 0
* Define a method to increase the speed by a given increment.
* Define a method to decrease the speed by a given decrement.

In [3]:
class Car:
    def __init__(self):
        self.__speed = 0

    def accelerate(self, increment):
        self.__speed += increment

    def decelerate(self, decrement):
        if self.__speed - decrement >= 0:
            self.__speed -= decrement

    def get_speed(self):
        return self.__speed

car = Car()
car.accelerate(50)
car.decelerate(20)
print(car.get_speed())  

30


Create a Shape class with a method area. Derive Circle, Rectangle, and Triangle classes from it. Implement different methods of calculating the area.

* import math library to use $\pi$ in the code. Syntax: import math; p = math.py
* Define an abstract method area() using pass as its implementation. This serves as a placeholder for derived classes to implement their own area method.

In [3]:
import math

class Shape:
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

class Triangle(Shape):
    def __init__(self, base, height):
        self.base = base
        self.height = height

    def area(self):
        return 0.5 * self.base * self.height


circle = Circle(5)
rectangle = Rectangle(4, 6)
triangle = Triangle(3, 4)
print(circle.area())  
print(rectangle.area())  
print(triangle.area())  

78.53981633974483
24
6.0


Create a Ticket class that encapsulates the ticket price and booking status. Implement methods to book and cancel a ticket.
* Initialize the ticket with a private attribute price to store its price.
* Initialize a private attribute is_booked to track the booking status. Set its initial value to False.
* Check if the ticket is already booked. If not booked, mark the corresponding private variable as booked and return a confirmation message with the ticket price. If already booked, return a message indicating that the ticket is already booked.
* In the cancel method, reset the status of the private variable and return a cancellation confirmation message. If not booked, return a message indicating there’s no ticket to cancel.

In [5]:
class Ticket:
    def __init__(self, price):
        self.__price = price
        self.__is_booked = False

    def book(self):
        if not self.__is_booked:
            self.__is_booked = True
            return f"Ticket booked for ${self.__price}"
        return "Ticket already booked"

    def cancel(self):
        if self.__is_booked:
            self.__is_booked = False
            return "Ticket canceled"
        return "No ticket to cancel"


ticket = Ticket(50)
print(ticket.book())  
print(ticket.cancel())  

Ticket booked for $50
Ticket canceled


Create a BankAccount class with methods for deposit and withdrawal. Derive a SavingsAccount class that adds interest to the balance.

* BankAccount class
    * Define constructor that initializes the account's balance attribute.
    * Implement a deposit method to add a specified amount to the balance.
    * Implement a withdraw method to subtract a specified amount from the balance if the amount is less than or equal to the balance.
* SavingsAccount class
    * Extend the constructor to initialize the balance attribute.
    * Add a new attribute interest_rate to store the savings account's interest rate.
    * Define an apply_interest method that calculates the interest based on the balance and interest_rate, then adds it to the balance.

In [6]:
class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount

class SavingsAccount(BankAccount):
    def __init__(self, balance, interest_rate):
        super().__init__(balance)
        self.interest_rate = interest_rate

    def apply_interest(self):
        self.balance += self.balance * self.interest_rate


account = SavingsAccount(1000, 0.05)
account.apply_interest()
print(account.balance)  

1050.0


Create a Matrix class with a method eigenvalues. Derive DiagonalMatrix and SymmetricMatrix classes, each implementing their own eigenvalue calculation.

In [7]:
import numpy as np

class Matrix:
    def __init__(self, values):
        self.__matrix = np.array(values)

    def eigenvalues(self):
        pass

    def is_symmetric(self):
        return np.array_equal(self.__matrix, self.__matrix.T)

    def get_matrix(self):
        return self.__matrix

class DiagonalMatrix(Matrix):
    def __init__(self, diagonal_values):
        super().__init__(np.diag(diagonal_values))

    def eigenvalues(self):
        return np.diagonal(self.get_matrix())

class SymmetricMatrix(Matrix):
    def __init__(self, values):
        super().__init__(values)

    def eigenvalues(self):
        return np.linalg.eigvals(self.get_matrix())

diag_matrix = DiagonalMatrix([1, 2, 3])
sym_matrix = SymmetricMatrix([[1, 2], [2, 1]])
non_sym_matrix = SymmetricMatrix([[1, 2], [3, 1]])

print(diag_matrix.eigenvalues())  
print(sym_matrix.eigenvalues())  
print(sym_matrix.is_symmetric())  
print(non_sym_matrix.is_symmetric())  

[1 2 3]
[ 3. -1.]
True
False


Create a Matrix class that encapsulates the matrix. Implement a method to calculate the trace of the matrix.

In [8]:
import numpy as np

class Matrix:
    def __init__(self, values):
        self.__matrix = np.array(values)

    def trace(self):
        return np.trace(self.__matrix)

    def get_matrix(self):
        return self.__matrix

m = Matrix([[1, 2], [3, 4]])
print(m.trace())  

5


Create a Regression class with a method fit. Derive LinearRegression and PolynomialRegression classes to implement their own fitting logic.

In [9]:
import numpy as np

class Regression:
    def fit(self, X, y):
        pass

class LinearRegression(Regression):
    def fit(self, X, y):
        return np.linalg.lstsq(X, y, rcond=None)[0]

class PolynomialRegression(Regression):
    def __init__(self, degree):
        self.degree = degree

    def fit(self, X, y):
        # Generate the design matrix for polynomial regression
        X_poly = np.hstack([X**i for i in range(self.degree + 1)])
        return np.linalg.lstsq(X_poly, y, rcond=None)[0]

# Test
X = np.array([1, 2, 3, 4]).reshape(-1, 1)  
y = np.array([2, 3, 5, 7])  

linear_model = LinearRegression()
poly_model = PolynomialRegression(degree=2)  

print(linear_model.fit(X, y))  
print(poly_model.fit(X, y))  

[1.7]
[1.25 0.45 0.25]


Create a Matrix class with a method for Singular Value Decomposition (SVD). Derive RectangularMatrix and SquareMatrix classes to implement SVD.

In [10]:
import numpy as np

class Matrix:
    def svd(self):
        pass

class RectangularMatrix(Matrix):
    def __init__(self, values):
        self.__matrix = np.array(values)

    def svd(self):
        return np.linalg.svd(self.__matrix)

class SquareMatrix(Matrix):
    def __init__(self, values):
        self.__matrix = np.array(values)

    def svd(self):
        return np.linalg.svd(self.__matrix)

rect_matrix = RectangularMatrix([[1, 2], [3, 4]])
square_matrix = SquareMatrix([[1, 2], [3, 4]])
print(rect_matrix.svd())  
print(square_matrix.svd()) 

(array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
(array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


Using inheritance and polymorphism to solve a system of linear equations for different matrix types without using in-built functions

In [11]:
import numpy as np

class GaussianElimination:
    def __init__(self, A, b):
        self.A = np.array(A, float)  
        self.b = np.array(b, float)  
        self.n = len(self.b) 
    
    def forward_elimination(self):
        for i in range(self.n):
            max_row = np.argmax(abs(self.A[i:, i])) + i
            self.A[[i, max_row]] = self.A[[max_row, i]]
            self.b[i], self.b[max_row] = self.b[max_row], self.b[i]

            for j in range(i + 1, self.n):
                if self.A[j, i] != 0:  
                    factor = self.A[j, i] / self.A[i, i]
                    self.A[j, i:] -= factor * self.A[i, i:]
                    self.b[j] -= factor * self.b[i]

    def back_substitution(self):
        x = np.zeros(self.n)
        for i in range(self.n - 1, -1, -1):
            x[i] = (self.b[i] - np.dot(self.A[i, i + 1:], x[i + 1:])) / self.A[i, i]
        return x

    def solve(self):
        self.forward_elimination()
        return self.back_substitution()

A = [[2, 1, -1], [3, 3, 9], [3, 3, 5]]
b = [8, -2, 3]

gaussian = GaussianElimination(A, b)
solution = gaussian.solve()

print("Solution to the system of equations:", solution)

Solution to the system of equations: [ 3.66666667 -0.58333333 -1.25      ]


Linear Regression (Encapsulation and Inheritance) without using in-built function

In [12]:
import numpy as np

class Regression:
    def fit(self, X, y):
        pass

class LinearRegression(Regression):
    def __init__(self):
        self.theta = None    
        X_b = self.add_bias(X)
        X_T = self.transpose(X_b)
        X_T_X = self.matrix_multiply(X_T, X_b)
        X_T_X_inv = self.inverse(X_T_X)
        X_T_y = self.matrix_multiply(X_T, y)
        self.theta = self.matrix_multiply(X_T_X_inv, X_T_y)
        
    def predict(self, X):
        X_b = self.add_bias(X)
        return self.matrix_multiply(X_b, self.theta)
    
    def add_bias(self, X):
        return np.c_[np.ones((X.shape[0], 1)), X]
    
    def transpose(self, matrix):
        return np.array(matrix).T
    
    def matrix_multiply(self, A, B):
        return np.dot(A, B)
    
    def inverse(self, matrix):
        return np.linalg.inv(matrix)
    

X = np.array([[1], [2], [3], [4]])  
y = np.array([2, 3, 5, 7])          

linear_model = LinearRegression()
linear_model.fit(X, y)
print("Learned parameters (theta):", linear_model.theta)
predictions = linear_model.predict(X)
print("Predictions:", predictions)

Learned parameters (theta): [0.  1.7]
Predictions: [1.7 3.4 5.1 6.8]


 LU Decomposition (Encapsulation and Polymorphism) without using inbuilt functions

In [13]:
import numpy as np

class MatrixDecomposition:
    def decompose(self, A):
        pass

class LUDecomposition(MatrixDecomposition):
    def __init__(self):
        self.L = None
        self.U = None
    
    def decompose(self, A):
        A = np.array(A, float)  
        n = A.shape[0]
        
        self.L = np.eye(n)
        self.U = A.copy()

        for i in range(n):
            for j in range(i + 1, n):
                if self.U[j, i] != 0: 
                    factor = self.U[j, i] / self.U[i, i]
                    self.L[j, i] = factor
                    self.U[j, i:] -= factor * self.U[i, i:]
        
        return self.L, self.U

class SymmetricLUDecomposition(LUDecomposition):
    def decompose(self, A):
        A = np.array(A, float)
        n = A.shape[0]
        
        self.L = np.zeros((n, n))
        self.U = np.zeros((n, n))
        
        for i in range(n):
            for j in range(i, n):
                if i == j:
                    self.U[i, i] = np.sqrt(A[i, i] - np.dot(self.L[i, :i], self.L[i, :i]))
                else:
                    self.L[j, i] = (A[j, i] - np.dot(self.L[j, :i], self.L[i, :i])) / self.U[i, i]
                    self.U[i, j] = A[i, j] - np.dot(self.L[i, :i], self.L[j, :i])
        
        return self.L, self.U

A = np.array([[4, 3], [6, 3]])
lu_decomp = LUDecomposition()
L, U = lu_decomp.decompose(A)

print("L (Lower Triangular Matrix):\n", L)
print("U (Upper Triangular Matrix):\n", U)

A_symmetric = np.array([[4, 1], [1, 3]])
symmetric_lu_decomp = SymmetricLUDecomposition()
L_sym, U_sym = symmetric_lu_decomp.decompose(A_symmetric)
print("\nL (Lower Triangular Matrix) for Symmetric Matrix:\n", L_sym)
print("U (Upper Triangular Matrix) for Symmetric Matrix:\n", U_sym)

L (Lower Triangular Matrix):
 [[1.  0. ]
 [1.5 1. ]]
U (Upper Triangular Matrix):
 [[ 4.   3. ]
 [ 0.  -1.5]]

L (Lower Triangular Matrix) for Symmetric Matrix:
 [[0.  0. ]
 [0.5 0. ]]
U (Upper Triangular Matrix) for Symmetric Matrix:
 [[2.        1.       ]
 [0.        1.6583124]]


Computing the Rank of a Matrix (without inbuilt functions)

In [14]:
import numpy as np

class MatrixOperations:
    def rank(self, matrix):
        pass

class RankMatrix(MatrixOperations):
    def __init__(self):
        self.matrix = None

    def rank(self, matrix):
        matrix = np.array(matrix, float)  
        m, n = matrix.shape
        
        row = 0
        for col in range(n):
            if row >= m:
                break

            pivot_row = row
            while pivot_row < m and matrix[pivot_row, col] == 0:
                pivot_row += 1

            if pivot_row == m:  
                continue
            
            matrix[[row, pivot_row]] = matrix[[pivot_row, row]]

            for i in range(row + 1, m):
                if matrix[i, col] != 0:
                    factor = matrix[i, col] / matrix[row, col]
                    matrix[i, col:] -= factor * matrix[row, col:]

            row += 1

        rank = 0
        for i in range(m):
            if any(matrix[i, j] != 0 for j in range(n)):  
                rank += 1
        return rank


A = np.array([[4, 3], [6, 3], [2, 2]])  
rank_matrix = RankMatrix()
rank = rank_matrix.rank(A)
print("Rank of the matrix:", rank)

Rank of the matrix: 2
